name: Auto Update
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1/4 * * *"
    
jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Set global directory
        run: git config --global --add safe.directory /github/workspace
        
      - uses: actions/checkout@v4     
        with:
          persist-credentials: false
          fetch-depth: 1
          
      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "syahrul19112003@gmail.com"
          git config --local user.name "Happy-Syahrul-Ramadhan"
          git add -A
          
          # Cek apakah ada perubahan sebelum commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git commit -m "what are you looking for 🦁?"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
